import NetflixLogo from'./Vector.svg'
import block from './Rectangle2.png'
import block1 from './Rectangle5.png'
import block2 from './Rectangle4.png'
import block3 from './Rectangle3.png'
import block4 from './Rectangle26.png'
import logo from './logo.png'
import circle from './Ellipse1.png'
import circle1 from './Ellipse2.png'
import circle2 from './Ellipse3.png'
import circle3 from './Ellipse4.png'
import Hs1 from './Hs1.png'
import Hs2 from './Hs2.png'
import Hs3 from './Hs3.png'
import Hs4 from './Hs4.png'
import Hs5 from './Hs5.png'
import Bg1 from './Bg1.png'
import Movie from './Movie.png'
import S1 from './S1.png'
import S2 from './S2.png'
import S3 from './S3.png'
import S4 from './S4.png'
import S5 from './S5.png'
import S6 from './S6.png'
import S7 from './S7.png'
import C1 from './C1.png'
import C2 from './C2.png'
import C3 from './C3.png'
import C4 from './C4.png'
import C5 from './C5.png'
import M1 from './M1.png'
import M8 from './M8.png'
import M2 from './M2.png'
import M3 from './M3.png'
import M4 from './M4.png'
import M5 from './M5.png'
import M6 from './M6.png'
import M7 from './M7.png'
import First from './First.mp4'
import First1 from './First1.mp4'
import First2 from './First2.mp4'
import First3 from './First3.mp4'


export{
    NetflixLogo, block1,block2,block3,block,block4,logo,circle1,circle2,circle,circle3,Hs1,Hs2,Hs3,Hs4,Hs5,Bg1,Movie,
    S1,S2,S3,S4,S5,S6,S7,C1,C2,C3,C4,C5,M1,M2,M3,M4,M5,M6,M7,M8,First,First1,First2,First3
}